# AWSテンプレートのバージョン 2020年1月現在はこれで固定
AWSTemplateFormatVersion: "2010-09-09"
# テンプレートの説明 実行時に表示されるので書いたほうがいい
Description: RailsTutorial CloudFormation template

# AWSの各リソースを定義
Resources: 
  # VPCの作成
  RailsTutorialVPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: 
      - Key: Name
        Value: cfn-rails-tutorial

  # プライベートサブネットの定義
  RailsTutorialSubnetPrivate1a: 
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: 
        Ref: RailsTutorialVPC
      Tags: 
      - Key: Name
        Value: cfn-private-subnet-1a

  RailsTutorialSubnetPrivate1c: 
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: 
        Ref: RailsTutorialVPC
      Tags: 
      - Key: Name
        Value: cfn-private-subnet-1c

  # パブリックサブネットの定義
  RailsTutorialSubnetPublic1a: 
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: 
        Ref: RailsTutorialVPC
      Tags: 
        - Key: Name
          Value: cfn-public-subnet-1a

  RailsTutorialSubnetPublic1c: 
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: 
        Ref: RailsTutorialVPC
      Tags: 
      - Key: Name
        Value: cfn-public-subnet-1c

  # インターネットゲートウェイの定義
  RailsTutorialInternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: cfn-rails-tutorial-internet-gateway

  # インターネットゲートウェイをVPCへアタッチ
  RailsTutorialInternetGatewayAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
        VpcId: 
          Ref: RailsTutorialVPC
        InternetGatewayId: 
          Ref: RailsTutorialInternetGateway

  # DHCPオプションセットの定義
  RailsTutorialInternetGatewayDHCPOptionset: 
    Type: AWS::EC2::DHCPOptions
    Properties: 
      DomainName: ap-northeast-1.compute.internal
      DomainNameServers: 
        - AmazonProvidedDNS
      Tags: 
        - Key: Name
          Value: cfn-rails-tutorial-dhcp-option

  # ネットワークACLの定義
  RailsTutorialNetworkAcl: 
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: 
        Ref: RailsTutorialVPC
      Tags: 
        - Key: Name
          Value: cfn-rails-tutorial-networkacl

  # ネットワークACLのインバウンドのルールの定義
  RailsTutorialNetworkAclEntryInbound: 
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: "true"
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: "100"
      NetworkAclId: 
        Ref: RailsTutorialNetworkAcl

  # ネットワークACLのアウトバウンドのルールの定義
  RailsTutorialNetworkAclEntryOutbound: 
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: "false"
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: "100"
      NetworkAclId: 
        Ref: RailsTutorialNetworkAcl

  # ネットワークACLをサブネットへ関連付け
  # ap-northeast-1a
  RailsTutorialSubnetNetworkAclAssociationApNorthEast1aPrivate1a: 
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: RailsTutorialNetworkAcl
      SubnetId: 
        Ref: RailsTutorialSubnetPrivate1a
  RailsTutorialSubnetNetworkAclAssociationApNorthEast1aPublic1a: 
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: RailsTutorialNetworkAcl
      SubnetId: 
        Ref: RailsTutorialSubnetPublic1a
  # ap-northeast-1c
  RailsTutorialSubnetNetworkAclAssociationApNorthEast1cPrivate1c: 
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: RailsTutorialNetworkAcl
      SubnetId: 
        Ref: RailsTutorialSubnetPrivate1c
  RailsTutorialSubnetNetworkAclAssociationApNorthEast1cPublic1c: 
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: RailsTutorialNetworkAcl
      SubnetId: 
        Ref: RailsTutorialSubnetPublic1c

  # ルートテーブルの定義
  RailsTutorialRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: 
        Ref: RailsTutorialVPC
      Tags: 
        - Key: Name
          Value: cfn-rails-tutorial-route-table
  
  # ルートテーブルにインターネットゲートウェイの設定をする
  RailsTutorialGatewayToInternetRouting: 
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: 
        Ref: RailsTutorialRouteTable
      GatewayId: 
        Ref: RailsTutorialInternetGateway
    # 先にインターネットゲートウェイをVPCとアタッチさせてから動作させる
    DependsOn: RailsTutorialInternetGatewayAttachment

  # ルートテーブルとサブネット(ap-northeast-1a-public1a)の関連付け
  RailsTutorialSubnetRouteTableAssociationApNorthEast1aPublic1a: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RailsTutorialRouteTable
      SubnetId: 
        Ref: RailsTutorialSubnetPublic1a

