# AWSテンプレートのバージョン 2020年1月現在はこれで固定
AWSTemplateFormatVersion: "2010-09-09"
# テンプレートの説明 実行時に表示されるので書いたほうがいい
Description: raisetech deploy-live-demo taskleaf template

# VPCの作成
Resources: 
  vpc001cb30c148fea2c7: 
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: "default"
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
      - Key: "Name"
        Value: "aws-deploy-live-demo"

  # サブネット定義
  subnet07fe47072981473fd:
      Type: "AWS::EC2::Subnet"
      Properties:
        CidrBlock: 10.0.2.0/24
        AvailabilityZone: "ap-northeast-1a"
        VpcId:
          Ref: "vpc001cb30c148fea2c7"
        Tags:
        - Key: "Name"
          Value: "プライベートサブネット1a"

  subnet04e0bc24795b2ee8a: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      CiderBlock: 10.0.3.0/24
      AvailabilityZone: "ap-northeast-1c"
      VpcId: 
        Ref: "vpc001cb30c148fea2c7"
      Tags: 
      - Key: "Name"
        Value: "プライベートサブネット1c"

  subnet0e7a6bab84fabe653:
      Type: "AWS::EC2::Subnet"
      Properties:
        CidrBlock: 10.0.0.0/24
        AvailabilityZone: "ap-northeast-1a"
        VpcId:
          Ref: "vpc001cb30c148fea2c7"
        Tags:
          - Key: "Name"
            Value: "パブリックサブネット1a"

  subnet0f9be3a04c782f494:
      Type: "AWS::EC2::Subnet"
      Properties:
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: "ap-northeast-1c"
        VpcId:
          Ref: "vpc001cb30c148fea2c7"
        Tags:
        - Key: "Name"
          Value: "パブリックサブネット1c"

  
 